CREATE OR REPLACE FUNCTION FUN_VALIDA_PRO_QTDE(ID_PRODUTO TB_PRODUTO.COD_PRODUTO%TYPE, PRO_QTDE TB_ITENSCARRINHO.QTDE%TYPE) RETURN BOOLEAN
IS
	TOTAL_ESTOQUE TB_PRODUTO.ESTOQUE_PRODUTO%TYPE;	
	
BEGIN
	--PEGA A QUANTIDADE EM ESTOQUE DO PRODUTO E VERIFICA SE O PRODUTO EXISTE--
	
	SELECT
		ESTOQUE_PRODUTO INTO TOTAL_ESTOQUE
	FROM
		TB_PRODUTO
	WHERE
		COD_PRODUTO = ID_PRODUTO;
	
	--RETORNA TRUE SE A QUANTIDADE EM ESTOQUE FOR MAIOR OU IGUAL A QUANTIDADE COLOCADA NO CARRINHO, CASO CONTRARIO RETORNA FALSE--
	
	RETURN (TOTAL_ESTOQUE >= PRO_QTDE);
	
EXCEPTION
	WHEN NO_DATA_FOUND THEN		
		RAISE_APPLICATION_ERROR(-20210, 'PRODUTO NÃO EXISTE!!!');
	WHEN OTHERS THEN		
		RAISE_APPLICATION_ERROR(-20211, 'ALGUM OUTRO ERRO OCORREU!!!');
END;