CREATE OR REPLACE PROCEDURE PROC_DEL_VENDA(ID_VENDA TB_VENDA.COD_VENDA%TYPE)
IS	
	MSG_ERRO VARCHAR2(512);
	
	ERRO_VEN_NULL EXCEPTION;
	ERRO_COD_VENDA EXCEPTION;
	
	ERRO_VENDA EXCEPTION;
	PRAGMA EXCEPTION_INIT(ERRO_VENDA, -20250);

BEGIN
	--VALIDA ENTRADA DE DADOS--
	
	IF ID_VENDA IS NULL THEN
		RAISE ERRO_VEN_NULL;	
	END IF;
	
	--FAZ A EXCLUSÃO LOGICA DA VENDA--
	
	UPDATE TB_VENDA SET IND_EXCLUIDO = 1 WHERE COD_VENDA = ID_VENDA;
	
	--VERIFICA SE ALGUMA VENDA FOI EXCLUIDA--
	
	IF SQL%ROWCOUNT = 0 THEN
		RAISE ERRO_COD_VENDA;
	END IF;

	COMMIT;
	DBMS_OUTPUT.PUT_LINE('VENDA EXCLUIDA COM SUCESSO!!!');
	
EXCEPTION
	WHEN ERRO_VEN_NULL THEN
		ROLLBACK;
		RAISE_APPLICATION_ERROR(-20240, 'ID DA VENDA NÃO PODE SER NULL!!!');
	WHEN ERRO_COD_VENDA THEN
		ROLLBACK;
		RAISE_APPLICATION_ERROR(-20241, 'ESSA VENDA NÃO EXISTE!!!');
	WHEN ERRO_VENDA THEN
		ROLLBACK;
		MSG_ERRO := SQLERRM;
		RAISE_APPLICATION_ERROR(-20242, MSG_ERRO);
	WHEN OTHERS THEN
		ROLLBACK;
		RAISE_APPLICATION_ERROR(-20243, 'ALGUM OUTRO ERRO OCORREU!!!');
END;