
--FAZ VENDA--

DECLARE
	ID_CLIENTE TB_CLIENTE.COD_CLIENTE%TYPE := 1;
	ID_FUNCIONARIO TB_FUNCIONARIO.COD_FUNCIONARIO%TYPE := 4;
	ID_PRODUTO TB_PRODUTO.COD_PRODUTO%TYPE;
	PRO_QTDE TB_ITENSCARRINHO.QTDE%TYPE;
	
	COD_ERRO NUMBER;
	MSG_ERRO VARCHAR2(512);	
	
	CURSOR PRO_CURSOR IS SELECT COD_PRODUTO, DESC_PRODUTO, ESTOQUE_PRODUTO FROM TB_PRODUTO;
BEGIN

	FOR PRO_RECORD IN PRO_CURSOR LOOP
		DBMS_OUTPUT.PUT_LINE('ID: ' || PRO_RECORD.COD_PRODUTO || '	QTDE: ' || PRO_RECORD.ESTOQUE_PRODUTO || '	PRODUTO: ' || PRO_RECORD.DESC_PRODUTO);
	END LOOP;
	DBMS_OUTPUT.PUT_LINE(chr(13));
	

	ID_PRODUTO := 2;
	PRO_QTDE := 1;
	PROC_ADD_ITENSCARRINHO(ID_CLIENTE, ID_PRODUTO, PRO_QTDE);
	
	ID_PRODUTO := 7;
	PRO_QTDE := 12;
	PROC_ADD_ITENSCARRINHO(ID_CLIENTE, ID_PRODUTO, PRO_QTDE);
	
	ID_PRODUTO := 6;
	PRO_QTDE := 22;
	PROC_ADD_ITENSCARRINHO(ID_CLIENTE, ID_PRODUTO, PRO_QTDE);
	DBMS_OUTPUT.PUT_LINE(chr(13));
	
	
	IF FUN_FECHA_VENDA(ID_CLIENTE, ID_FUNCIONARIO) THEN
		DBMS_OUTPUT.PUT_LINE('VENDA FINALIZADA!!!');
	ELSE
		DBMS_OUTPUT.PUT_LINE('OCORREU UM ERRO NA VENDA!!!');
	END IF;
	DBMS_OUTPUT.PUT_LINE(chr(13));
	
	
	FOR PRO_RECORD IN PRO_CURSOR LOOP
		DBMS_OUTPUT.PUT_LINE('ID: ' || PRO_RECORD.COD_PRODUTO || '	QTDE: ' || PRO_RECORD.ESTOQUE_PRODUTO || '	PRODUTO: ' || PRO_RECORD.DESC_PRODUTO);
	END LOOP;
	
EXCEPTION
	WHEN OTHERS THEN
		COD_ERRO := SQLCODE;
		MSG_ERRO := SQLERRM;
		DBMS_OUTPUT.PUT_LINE('CODIGO ERRO: ' || COD_ERRO || ' MENSAGEM: ' || MSG_ERRO);
END;







--------------------------------------------------------


--EXCLUI VENDA--



DECLARE
	ID_VENDA TB_VENDA.COD_VENDA%TYPE := 44;
	COD_ERRO NUMBER;
	MSG_ERRO VARCHAR2(512);
	
	CURSOR PRO_CURSOR IS SELECT COD_PRODUTO, DESC_PRODUTO, ESTOQUE_PRODUTO FROM TB_PRODUTO;
	
BEGIN

	FOR PRO_RECORD IN PRO_CURSOR LOOP
		DBMS_OUTPUT.PUT_LINE('ID: ' || PRO_RECORD.COD_PRODUTO || '	QTDE: ' || PRO_RECORD.ESTOQUE_PRODUTO || '	PRODUTO: ' || PRO_RECORD.DESC_PRODUTO);
	END LOOP;
	DBMS_OUTPUT.PUT_LINE(chr(13));

	PROC_DEL_VENDA(ID_VENDA);
	DBMS_OUTPUT.PUT_LINE(chr(13));
	
	FOR PRO_RECORD IN PRO_CURSOR LOOP
		DBMS_OUTPUT.PUT_LINE('ID: ' || PRO_RECORD.COD_PRODUTO || '	QTDE: ' || PRO_RECORD.ESTOQUE_PRODUTO || '	PRODUTO: ' || PRO_RECORD.DESC_PRODUTO);
	END LOOP;
	DBMS_OUTPUT.PUT_LINE(chr(13));
	
EXCEPTION
	WHEN OTHERS THEN
		COD_ERRO := SQLCODE;
		MSG_ERRO := SQLERRM;
		DBMS_OUTPUT.PUT_LINE('CODIGO ERRO: ' || COD_ERRO || ' MENSAGEM: ' || MSG_ERRO);
END;


