CREATE OR REPLACE TRIGGER TRI_ATUALIZA_ESTOQUE_2
BEFORE UPDATE OF IND_EXCLUIDO ON TB_VENDA
FOR EACH ROW
DECLARE
	CURSOR VEN_CURSOR IS	SELECT
								COD_PRODUTO, QTDE
							FROM
								TB_PRODUTOVENDA
							WHERE
								COD_VENDA = :OLD.COD_VENDA;	
BEGIN
	--VERIFICA SE ESSA VENDA JÁ NÃO FOI EXCLUIDA--
	
	IF :OLD.IND_EXCLUIDO = 1 THEN
		RAISE_APPLICATION_ERROR(-20250, 'ESSA VENDA JÁ FOI EXCLUIDA!!!');
	END IF;
	
	--CURSOR RETORNA TODOS OS ITENS DA VENDA EXCLUIDA--
	
	FOR VEN_RECORD IN VEN_CURSOR LOOP	
		--VOLTA OS ITENS PARA O ESTOQUE--
		
		UPDATE TB_PRODUTO SET ESTOQUE_PRODUTO = ESTOQUE_PRODUTO + VEN_RECORD.QTDE WHERE COD_PRODUTO = VEN_RECORD.COD_PRODUTO;
		
	END LOOP;
END;