CREATE OR REPLACE TRIGGER SECURE_EMP
BEFORE INSERT ON REGIONS
BEGIN
	IF TO_CHAR(SYSDATE, 'HH24:MI') NOT BETWEEN '08:00' AND '10:00' THEN
		RAISE_APPLICATION_ERROR(-20200, 'NÃO PODE INSERIR DADOS NESSE HORARIO');
	END IF;
END;


DECLARE
	WERRO EXCEPTION;
	PRAGMA EXCEPTION_INIT(WERRO, -20200);
BEGIN
	INSERT INTO REGIONS VALUES(600,'PARANA');
EXCEPTION
	WHEN WERRO THEN
		DBMS_OUTPUT.PUT_LINE('NÃO PODE INSERIR DADOS NESSE HORARIO');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('OCORREU ALGUM ERRO');
END;

----------------------------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER SECURE_EMP
BEFORE INSERT OR UPDATE OR DELETE ON REGIONS
BEGIN
	IF TO_CHAR(SYSDATE, 'HH24:MI') NOT BETWEEN '08:00' AND '10:00' THEN
		IF INSERTING THEN
			RAISE_APPLICATION_ERROR(-20201, 'NÃO PODE INSERIR DADOS NESSE HORARIO');
		ELSIF UPDATING THEN
			RAISE_APPLICATION_ERROR(-20202, 'NÃO PODE INSERIR DADOS NESSE HORARIO');
		ELSIF DELETING THEN
			RAISE_APPLICATION_ERROR(-20203, 'NÃO PODE INSERIR DADOS NESSE HORARIO');
		END IF;
	END IF;
END;

----------------------------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_LOG_EMPLOYEES
AFTER INSERT OR UPDATE OR DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
	INSERT INTO TB_LOG_EMPLOYEES(FIRST_NAME, NOVO_FIRST_NAME, SALARY, NOVO_SALARY, USUARIO, DATA) VALUES(:OLD.FIRST_NAME, :NEW.FIRST_NAME, :OLD.SALARY, :NEW.SALARY, USER, SYSDATE);
END;

----------------------------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_EMPLOYEES
BEFORE INSERT OR UPDATE ON EMPLOYEES
FOR EACH ROW
BEGIN
	:NEW.SALARY := 2000;
	:NEW.DEPARTMENT_ID := 90;
END;