DECLARE
	FNAME VARCHAR2(25);	
BEGIN
	SELECT FIRST_NAME INTO FNAME FROM EMPLOYEES WHERE EMPLOYEE_ID = 200;
	DBMS_OUTPUT.PUT_LINE('MEU NOME É: '||FNAME);
END;

--------------------------------------------------------------------------

DECLARE
	EMP_HIREDATE EMPLOYEES.HIRE_DATE%TYPE;
	EMP_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
	SELECT HIRE_DATE, SALARY INTO EMP_HIREDATE, EMP_SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
	DBMS_OUTPUT.PUT_LINE('DATA: '||EMP_HIREDATE||' SALARIO: '||EMP_SALARY);
END;

--------------------------------------------------------------------------

DECLARE
	SUM_SAL NUMBER(10, 2);
	DEPTNO INT NOT NULL := 60;
BEGIN
	SELECT SUM(SALARY) INTO SUM_SAL FROM EMPLOYEES WHERE DEPARTMENT_ID = DEPTNO;
	DBMS_OUTPUT.PUT_LINE('SOMA SALARIO: '||SUM_SAL);
END;

--------------------------------------------------------------------------

DECLARE
	SUM_SAL NUMBER(10, 2);
	DEPTNO INT NOT NULL := 60;
	DEP_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
	SELECT SUM(SALARY), DEPARTMENTS.DEPARTMENT_NAME INTO SUM_SAL, DEP_NAME
	FROM EMPLOYEES, DEPARTMENTS
	WHERE EMPLOYEES.DEPARTMENT_ID = DEPTNO
	AND
	EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
	GROUP BY DEPARTMENTS.DEPARTMENT_NAME;
	
	DBMS_OUTPUT.PUT_LINE('SOMA SALARIO: '||SUM_SAL||' DEPARTAMENTO: '||DEP_NAME);
END;

--------------------------------------------------------------------------

BEGIN
	UPDATE EMPLOYEES SET FIRST_NAME = 'NADA' WHERE EMPLOYEE_ID = 500;
	DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
END;