DECLARE
	V_NOME EMPLOYEES.LAST_NAME%TYPE;
BEGIN
	SELECT LAST_NAME INTO V_NOME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'JOHN';
	DBMS_OUTPUT.PUT_LINE(V_NOME);
EXCEPTION
	WHEN TOO_MANY_ROWS THEN
		DBMS_OUTPUT.PUT_LINE('EXISTE MAIS DE UM JOHN NO BANCO DE DADOS');
END;

-----------------------------------------------------------------------------------

DECLARE
	V_NOME EMPLOYEES.LAST_NAME%TYPE;
BEGIN
	SELECT LAST_NAME INTO V_NOME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'JOHN';
	DBMS_OUTPUT.PUT_LINE(V_NOME);
EXCEPTION
	WHEN TOO_MANY_ROWS THEN
		DBMS_OUTPUT.PUT_LINE('EXISTE MAIS DE UM JOHN NO BANCO DE DADOS');
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NÃO ENCONTROU EMPREGADO COM ESTE NOME NO BANCO DE DADOS');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('OCORREU UM ERRO');
END;

-----------------------------------------------------------------------------------

DECLARE
	INSERT_EXCEPTION EXCEPTION;
	PRAGMA EXCEPTION_INIT(INSERT_EXCEPTION, -1400);
BEGIN
	INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES(200, NULL);
EXCEPTION
	WHEN INSERT_EXCEPTION THEN
		DBMS_OUTPUT.PUT_LINE('OCORREU UM ERRO');
END;

-----------------------------------------------------------------------------------

DECLARE
	V_VALOR INT := 50;
	ERRO_SALARIO EXCEPTION;
BEGIN
	IF V_VALOR >= 100 THEN
		DBMS_OUTPUT.PUT_LINE('SALARIO ATUALIZADO PARA: ' || V_VALOR || ' REAIS');
	ELSE
		RAISE ERRO_SALARIO;
	END IF;
EXCEPTION
	WHEN ERRO_SALARIO THEN
		DBMS_OUTPUT.PUT_LINE('VALOR MENOR QUE 100 REAIS');
END;