DECLARE
	V_TEXT VARCHAR2(20) := 'Teste Teste Teste';
	V_NUM INTEGER;
BEGIN
	V_NUM := LENGTH(V_TEXT);
	DBMS_OUTPUT.PUT_LINE(V_NUM);
	V_TEXT := LOWER(V_TEXT);
	DBMS_OUTPUT.PUT_LINE(V_TEXT);
END;

------------------------------------------

DECLARE
	V_TEXT1 VARCHAR2(20) := 'Teste Teste Teste';	
BEGIN
	DECLARE		
		V_TEXT2 VARCHAR2(20) := 'etseT etseT etseT';
	BEGIN
		DBMS_OUTPUT.PUT_LINE('DEFINIDA NO BLOCO EXTERNO: '||V_TEXT1);
		DBMS_OUTPUT.PUT_LINE('DEFINIDA NO BLOCO INTERNO: '||V_TEXT2);
	END;
	DBMS_OUTPUT.PUT_LINE('FORA DO BLOCO: '||V_TEXT1);
END;

------------------------------------------

DECLARE
	V_NOMEPAI VARCHAR2(20) := 'PAFUNCIO';
	V_DTNASCIMENTO DATE := '20-04-1972';
BEGIN
	DECLARE		
		V_NOMEFILHO VARCHAR2(20) := 'JOÃO';
		V_DTNASCIMENTO DATE := '12-05-1992';
	BEGIN
		DBMS_OUTPUT.PUT_LINE('PAI: '||V_NOMEPAI);
		DBMS_OUTPUT.PUT_LINE('FILHO: '||V_NOMEFILHO);
		DBMS_OUTPUT.PUT_LINE('DATA NASCIMENTO FILHO: '||V_DTNASCIMENTO);
	END;
	DBMS_OUTPUT.PUT_LINE('DATA NASCIMENTO PAI: '||V_DTNASCIMENTO);
END;

------------------------------------------

<<BLOCO1>>
DECLARE
	V_NOMEPAI VARCHAR2(20) := 'PAFUNCIO';
	V_DTNASCIMENTO DATE := '20-04-1972';
BEGIN
	DECLARE		
		V_NOMEFILHO VARCHAR2(20) := 'JOÃO';
		V_DTNASCIMENTO DATE := '12-05-1992';
	BEGIN
		DBMS_OUTPUT.PUT_LINE('PAI: '||V_NOMEPAI);
		DBMS_OUTPUT.PUT_LINE('DATA NASCIMENTO PAI: '||BLOCO1.V_DTNASCIMENTO);
		DBMS_OUTPUT.PUT_LINE('FILHO: '||V_NOMEFILHO);
		DBMS_OUTPUT.PUT_LINE('DATA NASCIMENTO FILHO: '||V_DTNASCIMENTO);
	END;	
END;

------------------------------------------

DECLARE
	V_VALID BOOLEAN;
	EMPNO VARCHAR2(20) := 'A'; --VERIFICA SE EMPNO É NULL
BEGIN
	V_VALID :=(EMPNO IS NOT NULL);
	IF V_VALID THEN
		DBMS_OUTPUT.PUT_LINE('TRUE');
	END IF;
END;