DECLARE
	CURSOR EMP_CURSOR (DEPARTAMENTO EMP.DEPARTMENT_ID%TYPE, GERENTE EMP.MANAGER_ID%TYPE) IS SELECT EMPLOYEE_ID, SALARY, MANAGER_ID, DEPARTMENT_ID
																							FROM EMP
																							WHERE
																							MANAGER_ID = GERENTE
																							OR
																							DEPARTMENT_ID = DEPARTAMENTO
																							FOR UPDATE OF SALARY;
	V_DEPARTAMENTO EMP.DEPARTMENT_ID%TYPE := 50;
	V_GERENTE EMP.MANAGER_ID%TYPE := 100;
	V_SALARIO EMP.SALARY%TYPE;
	V_PERCENTUAL INT := 5;
	V_BONUS INT := 0;
BEGIN
	FOR EMP_RECORD IN EMP_CURSOR(V_DEPARTAMENTO,V_GERENTE) LOOP
		IF EMP_RECORD.DEPARTMENT_ID = V_DEPARTAMENTO AND EMP_RECORD.MANAGER_ID = V_GERENTE THEN
			V_BONUS := 3;
		ELSE
			IF EMP_RECORD.MANAGER_ID = V_GERENTE THEN
				V_BONUS := 2;
			END IF;
		END IF;
		DBMS_OUTPUT.PUT_LINE('ID: ' || EMP_RECORD.EMPLOYEE_ID || ' SALARIO: ' || EMP_RECORD.SALARY);
		V_SALARIO := EMP_RECORD.SALARY + (EMP_RECORD.SALARY * (V_PERCENTUAL + V_BONUS)/100);
		DBMS_OUTPUT.PUT_LINE('ID: ' || EMP_RECORD.EMPLOYEE_ID || ' SALARIO: ' || V_SALARIO);
		UPDATE EMP SET SALARY = V_SALARIO WHERE CURRENT OF EMP_CURSOR;
	END LOOP;
END;

----------------------------------------------------------------------------------

/*
Desenvolver um bloco anônimo para ler e armazenar em um cursor nome, salário dos empregados de um determinado departamento informado por parâmetro;
Calcular a média de salário dos funcionários deste departamento.
Conceder aumento salarial para os funcionários do departamento conforme tabela abaixo:

Media entre 0 - 3000 aumento 5%
Media entre 3000 - 7000 aumento 4%
Acima de 7000 aumento 3%

Escreva nome, salário atual
*/

DECLARE
	CURSOR EMP_CURSOR (DEPARTAMENTO EMPLOYEES.DEPARTMENT_ID%TYPE) IS SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE	DEPARTMENT_ID = DEPARTAMENTO FOR UPDATE OF SALARY;
	V_DEPARTAMENTO EMPLOYEES.DEPARTMENT_ID%TYPE := 50;
	V_AVGSALARIO EMPLOYEES.SALARY%TYPE;
	V_SALARIO EMPLOYEES.SALARY%TYPE;
	V_PERCENTUAL EMPLOYEES.SALARY%TYPE;
BEGIN
	SELECT AVG(SALARY) INTO V_AVGSALARIO FROM EMPLOYEES WHERE DEPARTMENT_ID = V_DEPARTAMENTO;
	DBMS_OUTPUT.PUT_LINE('MEDIA SALARIAL: ' || V_AVGSALARIO);
	FOR EMP_RECORD IN EMP_CURSOR(V_DEPARTAMENTO) LOOP
		IF V_AVGSALARIO >= 0 AND V_AVGSALARIO < 3000 THEN
			V_PERCENTUAL := 1.05;
		ELSE
			IF V_AVGSALARIO >= 3000 AND V_AVGSALARIO < 7000 THEN
				V_PERCENTUAL := 1.04;
			ELSE
				V_PERCENTUAL := 1.035;
			END IF;
		END IF;
		DBMS_OUTPUT.PUT_LINE('ID: ' || EMP_RECORD.FIRST_NAME || ' SALARIO: ' || EMP_RECORD.SALARY);
		V_SALARIO := EMP_RECORD.SALARY * V_PERCENTUAL;
		DBMS_OUTPUT.PUT_LINE('ID: ' || EMP_RECORD.FIRST_NAME || ' SALARIO: ' || V_SALARIO);
		UPDATE EMPLOYEES SET SALARY = V_SALARIO WHERE CURRENT OF EMP_CURSOR;
	END LOOP;
END;