CREATE OR REPLACE PROCEDURE ADD_JOBS(
  ID IN JOBS.JOB_ID%TYPE, TITULO IN JOBS.JOB_TITLE%TYPE, PMIN IN JOBS.MIN_SALARY%TYPE, PMAX IN JOBS.MAX_SALARY%TYPE) IS
  VERIFICA_SAL EXCEPTION;
  DESC_NULL EXCEPTION;
  PRAGMA EXCEPTION_INIT(DESC_NULL, -1400); ------INSERT NULL------
BEGIN
   IF PMIN > PMAX THEN
	RAISE VERIFICA_SAL;
   END IF;

   INSERT INTO JOBS(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES(ID, TITULO, PMIN, PMAX);
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('ID ' || ID||' EM USO.');
  WHEN VERIFICA_SAL THEN
    DBMS_OUTPUT.PUT_LINE('MIN SALARIO MAIOR QUE MAX SALARIO.');
  WHEN DESC_NULL THEN
    DBMS_OUTPUT.PUT_LINE('TITULO NÃO PODE SER NULL');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERRO!!!');
END;


---TESTE---
BEGIN
ADD_JOBS('AB','TESTE',100,200);
END;


--------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE UPD_JOBS(
  ID IN JOBS.JOB_ID%TYPE, TITULO IN JOBS.JOB_TITLE%TYPE) IS
  DESC_NULL EXCEPTION;
  PRAGMA EXCEPTION_INIT(DESC_NULL, -1407); ------UPDATE NULL-----
  NENHUMA_LINHA EXCEPTION;
BEGIN
   UPDATE JOBS SET JOB_TITLE = TITULO WHERE JOB_ID = ID;

   IF SQL%ROWCOUNT = 0 THEN
	RAISE NENHUMA_LINHA;
   END IF;

EXCEPTION
  WHEN NENHUMA_LINHA THEN
    DBMS_OUTPUT.PUT_LINE('NENHUMA LINHA ALTERADA.');

  WHEN DESC_NULL THEN
    DBMS_OUTPUT.PUT_LINE('TITULO NÃO PODE SER NULL');

  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERRO!!!');
END;


---TESTE---
BEGIN
UPD_JOBS('AB','PLSQL');
END;

--------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE DEL_JOBS(
  ID IN JOBS.JOB_ID%TYPE) IS
  DEL EXCEPTION;
  PRAGMA EXCEPTION_INIT(DEL, -02292);
  NENHUMA_LINHA EXCEPTION;
BEGIN
   DELETE FROM JOBS WHERE JOB_ID = ID;
   IF SQL%ROWCOUNT = 0 THEN
	RAISE NENHUMA_LINHA;
   END IF;
EXCEPTION
  WHEN NENHUMA_LINHA THEN
    DBMS_OUTPUT.PUT_LINE('NENHUMA LINHA ALTERADA.');
  WHEN DEL THEN
    DBMS_OUTPUT.PUT_LINE('NÃO PODE DELETAR UM REGISTRO PAI');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERRO!!!');
END;

---TESTE---
BEGIN
DEL_JOBS('AD_VP');
END;


------------------------------------

-------ERRO------------

CREATE OR REPLACE PROCEDURE GET_EMPLOYEE(ID IN EMPLOYEES.EMPLOYEE_ID%TYPE, SALARIO OUT EMPLOYEES.SALARY%TYPE, JOB OUT EMPLOYEES.JOB_ID%TYPE) IS
BEGIN
	SELECT SALARY, JOB_ID INTO SALARIO, JOB FROM EMPLOYEES WHERE EMPLOYEE_ID = ID;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NÃO EXISTE ESSE EMPREGADO.');
		JOB := 'NÃO EXISTE';
		SALARIO := 0;
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERRO!!!');
		JOB := 'NÃO EXISTE';
		SALARIO := 0;
END;