CREATE OR REPLACE PACKAGE COMM_PKG IS
	STD_COMM NUMBER := 0.10;
	PROCEDURE RESET_COMM(NEW_COMM NUMBER);
END COMM_PKG;

DECLARE
	WCOMISSAO NUMBER;
BEGIN
	WCOMISSAO := 100 * COMM_PKG.STD_COMM;
	DBMS_OUTPUT.PUT_LINE('VALOR COMISSAO: '||WCOMISSAO);
END;

CREATE OR REPLACE PACKAGE BODY COMM_PKG IS
	FUNCTION VALIDADE(COMM NUMBER) RETURN BOOLEAN IS
		MAX_COM EMPLOYEES.COMMISSION_PCT%TYPE;
	BEGIN
		SELECT MAX(COMMISSION_PCT) INTO MAX_COM FROM EMPLOYEES;
		RETURN (COMM BETWEEN 0.0 AND MAX_COM);
	END VALIDADE;
	
	PROCEDURE RESET_COMM(NEW_COMM NUMBER) IS
	BEGIN
		IF VALIDADE(NEW_COMM) THEN
			STD_COMM := NEW_COMM;
		ELSE
			RAISE_APPLICATION_ERROR(-20200,'ERRO DE COMISSAO');
		END IF;
	END RESET_COMM;
END COMM_PKG;


BEGIN
	COMM_PKG.RESET_COMM(0.3);
	DBMS_OUTPUT.PUT_LINE('COMISSAO: ' || COMM_PKG.STD_COMM);
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERRO!!!');
END;