DECLARE
	CURSOR EMP_CURSOR IS SELECT DEPARTMENT_ID, DEPARTMENT_NAME
						 FROM DEPARTMENTS
						 WHERE DEPARTMENT_ID < 100;
	CURSOR EMP_CURSOR2 (DEPTNO_ID DEPARTMENTS.DEPARTMENT_ID%TYPE) IS SELECT LAST_NAME, JOB_TITLE, SALARY, TO_CHAR(HIRE_DATE,'DD/MM/YYYY') AS DATA
																	  FROM EMPLOYEES, JOBS
																	  WHERE EMPLOYEES.JOB_ID = JOBS.JOB_ID AND EMPLOYEE_ID < 120 AND DEPARTMENT_ID = DEPTNO_ID;
	EMP_RECORD EMP_CURSOR%ROWTYPE;
	EMP_RECORD2 EMP_CURSOR2%ROWTYPE;
BEGIN
	OPEN EMP_CURSOR;
	LOOP
		FETCH EMP_CURSOR INTO EMP_RECORD;
		EXIT WHEN EMP_CURSOR%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE('ID: ' || EMP_RECORD.DEPARTMENT_ID || ' DEPARTAMENTO: ' || EMP_RECORD.DEPARTMENT_NAME);
		OPEN EMP_CURSOR2(EMP_RECORD.DEPARTMENT_ID);
		LOOP
			FETCH EMP_CURSOR2 INTO EMP_RECORD2;
			EXIT WHEN EMP_CURSOR2%NOTFOUND;
			DBMS_OUTPUT.PUT_LINE('SOBRENOME: ' || EMP_RECORD2.LAST_NAME || ' FUNÇÃO: ' || EMP_RECORD2.JOB_TITLE || ' SALARIO: ' || EMP_RECORD2.SALARY || ' DATA ADMISSÃO: ' || EMP_RECORD2.DATA);			
		END LOOP;
		CLOSE EMP_CURSOR2;
	END LOOP;
	CLOSE EMP_CURSOR;
END;