DECLARE
	CURSOR EMP IS SELECT DISTINCT(SALARY) AS SALARIO FROM EMPLOYEES ORDER BY SALARY;
	EMP_RECORD EMP%ROWTYPE;
	CONT INTEGER := 0;
BEGIN
	OPEN EMP;
	LOOP
		FETCH EMP INTO EMP_RECORD;
		EXIT WHEN EMP%NOTFOUND OR CONT = 5;
		DBMS_OUTPUT.PUT_LINE(EMP_RECORD.SALARIO);
		INSERT INTO TP_SALARIES VALUES (EMP_RECORD.SALARIO);
		CONT := CONT + 1;
	END LOOP;
	CLOSE EMP;
END;