DECLARE
	COUNTRY_RECORD COUNTRIES%ROWTYPE;
BEGIN
	SELECT * INTO COUNTRY_RECORD FROM COUNTRIES WHERE COUNTRY_ID = 'CA';
	DBMS_OUTPUT.PUT_LINE('CODIGO: '||COUNTRY_RECORD.COUNTRY_ID||' COUNTRY NAME: '||COUNTRY_RECORD.COUNTRY_NAME||'REGION: '||COUNTRY_RECORD.REGION_ID);
END;