DECLARE	
	FNAME EMPLOYEES.FIRST_NAME%TYPE;
	EMP_SAL EMPLOYEES.SALARY%TYPE;
	V_SAL EMPLOYEES.SALARY%TYPE;
	EMPNO EMPLOYEES.EMPLOYEE_ID%TYPE;
BEGIN
	SELECT FIRST_NAME, SALARY INTO FNAME, EMP_SAL FROM EMPLOYEES WHERE EMPLOYEE_ID = &EMPNO;
	DBMS_OUTPUT.PUT_LINE('OLÁ '||FNAME);
	V_SAL := EMP_SAL * 0.45 * 0.12;
	DBMS_OUTPUT.PUT_LINE('SALARIO: '||EMP_SAL||' CONTA: '||V_SAL);
END;