CREATE TABLE MESSAGES
(
	RESULTS VARCHAR2(80)
);

DECLARE
	EMP_NOME EMPLOYEES.LAST_NAME%TYPE;
	EMP_SAL EMPLOYEES.SALARY%TYPE := 24000;
BEGIN
	SELECT LAST_NAME INTO EMP_NOME FROM EMPLOYEES WHERE SALARY = EMP_SAL;
	INSERT INTO MESSAGES(RESULTS) VALUES ('NOME: ' || EMP_NOME || ' SALARIO: ' || EMP_SAL);
EXCEPTION
	WHEN TOO_MANY_ROWS THEN
		INSERT INTO MESSAGES(RESULTS) VALUES ('EXISTE MAIS DE UMA PESSOA COM ESSE SALARIO NO BANCO ' || EMP_SAL);	
	WHEN NO_DATA_FOUND THEN
		INSERT INTO MESSAGES(RESULTS) VALUES ('NÃO ENCONTROU EMPREGADO COM ESTE SALARIO NO BANCO ' || EMP_SAL);
	WHEN OTHERS THEN
		INSERT INTO MESSAGES(RESULTS) VALUES ('OCORREU UM ERRO');
END;

SELECT * FROM MESSAGES