DECLARE
	CURSOR EMP_CURSOR IS SELECT LAST_NAME, SALARY, MANAGER_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = 10;
BEGIN
	FOR EMP_RECORD IN EMP_CURSOR LOOP
		IF EMP_RECORD.SALARY < 5000 AND (EMP_RECORD.MANAGER_ID = 101 OR EMP_RECORD.MANAGER_ID = 124) THEN
			DBMS_OUTPUT.PUT_LINE('NOME: ' || EMP_RECORD.LAST_NAME || ' DUE FOR A RAISE');
		ELSE
			DBMS_OUTPUT.PUT_LINE('NOME: ' || EMP_RECORD.LAST_NAME || ' NOT DUE FOR A RAISE');
		END IF;
	END LOOP;
END;