DO
$$
DECLARE	
	MAX_DEPTNO DEPARTMENTS.DEPARTMENT_ID%TYPE;
BEGIN
	SELECT MAX(DEPARTMENT_ID) INTO MAX_DEPTNO FROM DEPARTMENTS;		
	RAISE NOTICE '%', MAX_DEPTNO;	
END;
$$


VARIABLE DEPT_ID NUMBER;

UPDATE table_name
SET column1 = value1, column2 = value2, ...
WHERE condition;

DELETE FROM table_name
WHERE condition;