DO
$$
DECLARE
	COUNTRY_RECORD COUNTRIES%ROWTYPE;
BEGIN
	SELECT * INTO COUNTRY_RECORD FROM COUNTRIES WHERE COUNTRY_ID = 'CA';
	RAISE NOTICE 'CODIGO: %, COUNTRY NAME: %, REGION: %', COUNTRY_RECORD.COUNTRY_ID, COUNTRY_RECORD.COUNTRY_NAME, COUNTRY_RECORD.REGION_ID;
END;
$$