DO
$$
DECLARE	
	FNAME TEXT;
	EMP_SAL EMPLOYEES.SALARY%TYPE;
	V_SAL EMPLOYEES.SALARY%TYPE;
	EMPNO EMPLOYEES.EMPLOYEE_ID%TYPE;
BEGIN
	SELECT FIRST_NAME, SALARY INTO FNAME, EMP_SAL FROM EMPLOYEES WHERE EMPLOYEE_ID = &EMPNO;
	RAISE NOTICE 'OLÁ %', FNAME;
	V_SAL := EMP_SAL * 0.45 * 0.12;
	RAISE NOTICE '%, %', EMP_SAL, V_SAL;
END;
$$