--CRIAR TABELA EMP COM VALORES DA TABELA EMPLOYEES.
SELECT * INTO EMP FROM EMPLOYEES;

ALTER TABLE EMP ADD STARS VARCHAR(50);

SELECT ROUND(SALARY /1000) FROM EMP WHERE EMPLOYEE_ID = 176;

SELECT SALARY, STARS FROM EMP WHERE EMPLOYEE_ID = 176;

--BLOCO PARA ADICIONAR '*' A CADA 1000 REAIS DO SALARIO
DO
$$
DECLARE
	EMPNO EMP.EMPLOYEE_ID%TYPE := 176;
	ASTERISK EMP.STARS%TYPE := '';
	SAL EMP.SALARY%TYPE;
BEGIN
	SELECT SALARY INTO SAL FROM EMP WHERE EMPLOYEE_ID = EMPNO;
	
	FOR I IN 1..ROUND(SAL /1000) LOOP
		ASTERISK := ASTERISK || '*';
	END LOOP;
	
	UPDATE EMP SET STARS = ASTERISK WHERE EMPLOYEE_ID = 176;
END;
$$
-----------------------------------------------------------------
--BLOCO PARA ADICIONAR '*' A CADA 1000 REAIS DO SALARIO USANDO CURSOR
DO
$$
DECLARE
	ASTERISK EMP.STARS%TYPE := '';
	SAL REFCURSOR;
	REC_SAL RECORD;
BEGIN
	OPEN SAL FOR SELECT EMPLOYEE_ID AS ID, ROUND(SALARY / 1000) AS SALARIO FROM EMP;
	LOOP FETCH SAL INTO REC_SAL;
		EXIT WHEN NOT FOUND;
		FOR I IN 1..REC_SAL.SALARIO LOOP
			ASTERISK := ASTERISK || '*';
		END LOOP;
		UPDATE EMP SET STARS = ASTERISK WHERE EMPLOYEE_ID = REC_SAL.ID;
		ASTERISK := '';
	END LOOP;
END;
$$