DO
$$
DECLARE
	EMP_CURSOR CURSOR IS SELECT LAST_NAME, SALARY, MANAGER_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = 10;
BEGIN
	FOR EMP_RECORD IN EMP_CURSOR LOOP
		IF EMP_RECORD.SALARY < 5000 AND (EMP_RECORD.MANAGER_ID = 101 OR EMP_RECORD.MANAGER_ID = 124) THEN
			RAISE NOTICE 'NOME: %, DUE FOR A RAISE', EMP_RECORD.LAST_NAME;
		ELSE
			RAISE NOTICE 'NOME: %, NOT DUE FOR A RAISE', EMP_RECORD.LAST_NAME;
		END IF;
	END LOOP;
END;
$$