DECLARE
	TODAY DATE := SYSDATE;
	TOMORROW TODAY%TYPE := TODAY + 1;
BEGIN
	DBMS_OUTPUT.PUT_LINE('OLÁ MUNDO!' || ' ' || TODAY || ' ' || TOMORROW);
END;

DO
$$
DECLARE
	TODAY DATE := CURRENT_DATE;
	TOMORROW TODAY%TYPE := TODAY + 1;
BEGIN
	RAISE NOTICE 'OLÁ MUNDO! % %', TODAY, TOMORROW;
END;
$$