DO
$$
DECLARE	
	MAX_DEPTNO DEPARTMENTS.DEPARTMENT_ID%TYPE;
	RES INTEGER;
BEGIN
	SELECT MAX(DEPARTMENT_ID) INTO MAX_DEPTNO FROM DEPARTMENTS;	
	UPDATE DEPARTMENTS SET LOCATION_ID = 3000 WHERE DEPARTMENT_ID = MAX_DEPTNO;			
END;
$$

SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID = 280;

DELETE FROM DEPARTMENTS WHERE DEPARTMENT_ID = 280;