SLIDE 05

DO
$$
DECLARE
	
BEGIN
	FOR I IN 1..10 LOOP
		IF I != 6 AND I != 8 THEN
			INSERT INTO RESULTS(RESULT) VALUES (I);
		END IF;
	END LOOP;
END;
$$
-----------------------------------------------------

SELECT * INTO EMP FROM EMPLOYEES;

ALTER TABLE EMP ADD STARS VARCHAR(50);

SELECT ROUND(SALARY /1000) FROM EMP WHERE EMPLOYEE_ID = 176;

SELECT SALARY, STARS FROM EMP WHERE EMPLOYEE_ID = 176;

DO
$$
DECLARE
	EMPNO EMP.EMPLOYEE_ID%TYPE := 176;
	ASTERISK EMP.STARS%TYPE := '';
	SAL EMP.SALARY%TYPE;
BEGIN
	SELECT SALARY INTO SAL FROM EMP WHERE EMPLOYEE_ID = EMPNO;
	
	FOR I IN 1..ROUND(SAL /1000) LOOP
		ASTERISK := ASTERISK || '*';
	END LOOP;
	
	UPDATE EMP SET STARS = ASTERISK WHERE EMPLOYEE_ID = 176;
END;
$$