DO
$$
DECLARE
	V_CURSOR REFCURSOR;
	V_REF RECORD;
BEGIN
	OPEN V_CURSOR FOR SELECT EMPLOYEE_ID AS ID FROM EMPLOYEES;
	LOOP FETCH V_CURSOR INTO V_REF;
		EXIT WHEN NOT FOUND;
		RAISE NOTICE '%', V_REF.ID;
	END LOOP;
END;
$$
---------------------------------------