DO
$$
DECLARE
	NOTA_CURSOR CURSOR IS SELECT COD_NOTA, VL_DESCONTO
						 FROM TB_NOTA;
	NOTA_ITEM_CURSOR CURSOR (NOTA_ID TB_NOTA.COD_NOTA%TYPE) IS SELECT SUM(QT_QUANTIDADE * VL_UNITARIO) AS TOTAL
																	  FROM TB_NOTA, TB_NOTA_ITEM
																	  WHERE TB_NOTA_ITEM.COD_NOTA = TB_NOTA.COD_NOTA 
																	  AND
																	  TB_NOTA_ITEM.COD_NOTA = NOTA_ID;
	NOTA_RECORD RECORD;
	NOTA_ITEM_RECORD RECORD;
BEGIN
	OPEN NOTA_CURSOR;
	LOOP
		FETCH NOTA_CURSOR INTO NOTA_RECORD;
		EXIT WHEN NOT FOUND;
		RAISE NOTICE 'ID: %, DESCONTO: %', NOTA_RECORD.COD_NOTA, NOTA_RECORD.VL_DESCONTO;
		OPEN NOTA_ITEM_CURSOR(NOTA_RECORD.COD_NOTA);
		LOOP
			FETCH NOTA_ITEM_CURSOR INTO NOTA_ITEM_RECORD;
			EXIT WHEN NOT FOUND;
			RAISE NOTICE 'VALOR TOTAL: %', NOTA_ITEM_RECORD.TOTAL;
			UPDATE TB_NOTA_ITEM SET VL_DESCONTO = (QT_QUANTIDADE * VL_UNITARIO * (NOTA_RECORD.VL_DESCONTO / NOTA_ITEM_RECORD.TOTAL)) WHERE COD_NOTA = NOTA_RECORD.COD_NOTA;
		END LOOP;
		CLOSE NOTA_ITEM_CURSOR;
	END LOOP;
	CLOSE NOTA_CURSOR;
END;
$$