DO
$$
DECLARE
	SAL CURSOR IS SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID = 30;
	EMPNO EMPLOYEES.EMPLOYEE_ID%TYPE;
	LNAME EMPLOYEES.LAST_NAME%TYPE;
BEGIN
	OPEN SAL;
	FETCH SAL INTO EMPNO, LNAME;
	RAISE NOTICE 'ID: %, NOME: %', EMPNO, LNAME;
	CLOSE SAL;
END;
$$

-----------------------------------------------------------------

DO
$$
DECLARE
	SAL CURSOR IS SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID = 30;
	EMPNO EMPLOYEES.EMPLOYEE_ID%TYPE;
	LNAME EMPLOYEES.LAST_NAME%TYPE;
BEGIN
	OPEN SAL;
	LOOP
		FETCH SAL INTO EMPNO, LNAME;
		EXIT WHEN NOT FOUND;
		RAISE NOTICE 'ID: %, NOME: %', EMPNO, LNAME;
	END LOOP;
	CLOSE SAL;
END;
$$

-----------------------------------------------------------------

DO
$$
DECLARE
	EMP CURSOR IS SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID = 30;
	EMP_RECORD EMP%ROWTYPE;
BEGIN
	OPEN EMP;
	LOOP
		FETCH EMP INTO EMP_RECORD;
		EXIT WHEN NOT FOUND;
		RAISE NOTICE 'ID: %, NOME: %', EMP_RECORD.EMPLOYEE_ID, EMP_RECORD.LAST_NAME;
	END LOOP;
	CLOSE EMP;
END;
$$

-----------------------------------------------------------------

DO
$$
DECLARE
	EMP CURSOR IS SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID = 30;
BEGIN
	FOR EMP_RECORD IN EMP LOOP
		RAISE NOTICE 'ID: %, NOME: %', EMP_RECORD.EMPLOYEE_ID, EMP_RECORD.LAST_NAME;
	END LOOP;
END;
$$

-----------------------------------------------------------------

DO
$$
DECLARE
	EMP CURSOR (DEPTNO_ID EMPLOYEES.DEPARTMENT_ID%TYPE) IS SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID = DEPTNO_ID;
	EMP_RECORD RECORD;
BEGIN
	RAISE NOTICE 'DEPARTAMENTO 10';
	OPEN EMP(10);
	LOOP
		FETCH EMP INTO EMP_RECORD;
		EXIT WHEN NOT FOUND;
		RAISE NOTICE 'ID: %, NOME: %', EMP_RECORD.EMPLOYEE_ID, EMP_RECORD.LAST_NAME;
	END LOOP;
	CLOSE EMP;
	RAISE NOTICE 'DEPARTAMENTO 20';
	OPEN EMP(20);
	LOOP
		FETCH EMP INTO EMP_RECORD;
		EXIT WHEN NOT FOUND;
		RAISE NOTICE 'ID: %, NOME: %', EMP_RECORD.EMPLOYEE_ID, EMP_RECORD.LAST_NAME;
	END LOOP;
	CLOSE EMP;
END;
$$

-----------------------------------------------------------------

DO
$$
DECLARE
	EMP CURSOR (DEPTNO_ID EMPLOYEES.DEPARTMENT_ID%TYPE) IS SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID = DEPTNO_ID FOR UPDATE;
	EMP_RECORD RECORD;
BEGIN
	RAISE NOTICE 'DEPARTAMENTO 10';
	OPEN EMP(10);
	LOOP
		FETCH EMP INTO EMP_RECORD;
		EXIT WHEN NOT FOUND;
		RAISE NOTICE 'ID: %, NOME: %', EMP_RECORD.EMPLOYEE_ID, EMP_RECORD.LAST_NAME;
		UPDATE EMPLOYEES SET SALARY = 10 WHERE CURRENT OF EMP;
	END LOOP;
	CLOSE EMP;
END;
$$