DO
$$
DECLARE
	EMP_REC EMPLOYEES%ROWTYPE;
BEGIN
	SELECT * INTO EMP_REC FROM EMPLOYEES WHERE EMPLOYEE_ID = 124;
	RAISE NOTICE 'CODIGO: %, NOME: %, SOBRENOME: %', EMP_REC.EMPLOYEE_ID, EMP_REC.FIRST_NAME, EMP_REC.LAST_NAME;
END;
$$

--------------------------------------------------------------------------------------------

SELECT * INTO EMPREGADO FROM EMPLOYEES WHERE EMPLOYEE_ID = -1;

--EXEMPLO INSERT USANDO %ROWTYPE
DO
$$
DECLARE
	EMP_REC EMPLOYEES%ROWTYPE;
BEGIN
	SELECT * INTO EMP_REC FROM EMPLOYEES WHERE EMPLOYEE_ID = 124;
	RAISE NOTICE 'CODIGO: %, NOME: %, SOBRENOME: %', EMP_REC.EMPLOYEE_ID, EMP_REC.FIRST_NAME, EMP_REC.LAST_NAME;
	INSERT INTO EMPREGADO VALUES (EMP_REC.*);
END;
$$

--EXEMPLO UPDATE USANDO %ROWTYPE

DO
$$
DECLARE
	EMP_REC EMPREGADO%ROWTYPE;
BEGIN
	SELECT * INTO EMP_REC FROM EMPREGADO WHERE EMPLOYEE_ID = 124;
	RAISE NOTICE 'CODIGO: %, NOME: %, SOBRENOME: %', EMP_REC.EMPLOYEE_ID, EMP_REC.FIRST_NAME, EMP_REC.LAST_NAME;
	EMP_REC.FIRST_NAME := 'UNIVERSIDADE';
	EMP_REC.LAST_NAME := 'FEDERAL';
	RAISE NOTICE 'CODIGO: %, NOME: %, SOBRENOME: %', EMP_REC.EMPLOYEE_ID, EMP_REC.FIRST_NAME, EMP_REC.LAST_NAME;
	UPDATE EMPREGADO SET ROW = EMP_REC WHERE EMPLOYEE_ID = 124;
END;
$$
-------------------------------------------------------------------------------------------

DO
$$
DECLARE
	TYPE EMP_REC_TYPE IS RECORD
		(CODIGO EMPLOYEES.EMPLOYEE_ID%TYPE,
		 NOME EMPLOYEES.FIRST_NAME%TYPE,
		 SOBRENOME EMPLOYEES.LAST_NAME%TYPE);
	EMP_REC EMP_REC_TYPE;
BEGIN
	SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME INTO EMP_REC FROM EMPREGADO WHERE EMPLOYEE_ID = 124;
	RAISE NOTICE 'CODIGO: %, NOME: %, SOBRENOME: %', EMP_REC.CODIGO, EMP_REC.NOME, EMP_REC.SOBRENOME;	
END;
$$

-------------------------------------------------------------------------------------------

