DO
$$
DECLARE
	V_NOME EMPLOYEES.LAST_NAME%TYPE;
BEGIN
	SELECT LAST_NAME INTO STRICT V_NOME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'JOHN';
	RAISE NOTICE '%', V_NOME;
EXCEPTION
	WHEN TOO_MANY_ROWS THEN
		RAISE NOTICE 'EXISTE MAIS DE UM JOHN NO BANCO DE DADOS';
END;
$$

-----------------------------------------------------------------------------------

DO
$$
DECLARE
	V_NOME EMPLOYEES.LAST_NAME%TYPE;
BEGIN
	SELECT LAST_NAME INTO STRICT V_NOME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'JOHN';
	RAISE NOTICE '%', V_NOME;
EXCEPTION
	WHEN TOO_MANY_ROWS THEN
		RAISE NOTICE 'EXISTE MAIS DE UM JOHN NO BANCO DE DADOS';
	WHEN NO_DATA_FOUND THEN
		RAISE NOTICE 'NÃO ENCONTROU EMPREGADO COM ESTE NOME NO BANCO DE DADOS';
	WHEN OTHERS THEN
		RAISE NOTICE 'OCORREU UM ERRO';
END;
$$

---------------------------------------------

DO
$$
DECLARE
	INSERT_EXCEPTION EXCEPTION;
	PRAGMA EXCEPTION_INIT(INSERT_EXCEPTION, -1400);
BEGIN
	INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES(200, NULL);
EXCEPTION
	WHEN INSERT_EXCEPTION
		RAISE EXCEPTION 'OCORREU UM ERRO';
END;
$$

DO
$$
BEGIN
	INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME) VALUES(200, NULL);
EXCEPTION
	WHEN NOT_NULL_VIOLATION THEN
		RAISE EXCEPTION 'NOME DO DEPARTAMENTO NÃO PODE SER NULL';
END;
$$

---------------------------------------------------

DO
$$
DECLARE
	V_VALOR INT := 50;
BEGIN
	IF V_VALOR >= 100 THEN
		RAISE NOTICE 'SALARIO ATUALIZADO PARA: % REAIS', V_VALOR;
	ELSE
		RAISE EXCEPTION 'VALOR MENOR QUE 100 REAIS:  %', V_VALOR;
	END IF;
	RAISE NOTICE 'TESTE DE EXCEPTION';
END;
$$

------
GET DIAGNOSTICS RES = ROW_COUNT;
------