DO
$$
DECLARE
	FNAME VARCHAR(25);	
BEGIN
	SELECT FIRST_NAME INTO FNAME FROM EMPLOYEES WHERE EMPLOYEE_ID = 200;
	RAISE NOTICE 'MEU NOME É %', FNAME;
END;
$$
--------------------------------------------------------------------------

DO
$$
DECLARE
	EMP_HIREDATE EMPLOYEES.HIRE_DATE%TYPE;
	EMP_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
	SELECT HIRE_DATE, SALARY INTO EMP_HIREDATE, EMP_SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
	RAISE NOTICE 'DATA: %, SALARIO: %', EMP_HIREDATE, EMP_SALARY;
END;
$$
--------------------------------------------------------------------------

DO
$$
DECLARE
	SUM_SAL NUMERIC(10, 2);
	DEPTNO NUMERIC NOT NULL := 60;
BEGIN
	SELECT SUM(SALARY) INTO SUM_SAL FROM EMPLOYEES WHERE DEPARTMENT_ID = DEPTNO;
	RAISE NOTICE 'SOMA SALARIO %', SUM_SAL;
END;
$$
---------------------------------------------------------------------------

DO
$$
DECLARE
	SUM_SAL NUMERIC(10, 2);
	DEPTNO NUMERIC NOT NULL := 60;
	DEP_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
	SELECT SUM(SALARY), DEPARTMENTS.DEPARTMENT_NAME INTO SUM_SAL, DEP_NAME
	FROM EMPLOYEES, DEPARTMENTS
	WHERE EMPLOYEES.DEPARTMENT_ID = DEPTNO
	AND
	EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
	GROUP BY DEPARTMENTS.DEPARTMENT_NAME;
	
	RAISE NOTICE 'SOMA SALARIO %, DEPARTAMENTO: %', SUM_SAL, DEP_NAME;
END;
$$
---------------------------------------------------------------------------

DO
$$
DECLARE
	RES INTEGER;
BEGIN
	UPDATE EMPLOYEES SET FIRST_NAME = 'NADA' WHERE EMPLOYEE_ID = 500;
	GET DIAGNOSTICS RES = ROW_COUNT;
	RAISE NOTICE '%', RES;
END;
$$