1-
DO
$$
DECLARE
	EMPNO EMPLOYEES.EMPLOYEE_ID%TYPE := 150;
	V_NOME EMPLOYEES.FIRST_NAME%TYPE;
	V_DEPNAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
	SELECT FIRST_NAME, DEPARTMENT_NAME INTO V_NOME, V_DEPNAME
	FROM EMPLOYEES EMP, DEPARTMENTS DEP
	WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
	AND
	EMP.EMPLOYEE_ID = EMPNO;
	
	RAISE NOTICE 'NOME: %, DEPARTAMENTO: %', V_NOME, V_DEPNAME;
END;
$$

2-
DO
$$
DECLARE
	RES INTEGER;
BEGIN
	DELETE FROM JOB_HISTORY WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'NANDITA');
	GET DIAGNOSTICS RES = ROW_COUNT;
	RAISE NOTICE 'FORAM EXCLUIDOS %', RES;
END;
$$

3-
DO
$$
DECLARE
	RES INTEGER;
BEGIN
	UPDATE EMPLOYEES SET SALARY = SALARY * 1.10 WHERE MANAGER_ID = 121;
	GET DIAGNOSTICS RES = ROW_COUNT;
	IF RES = 0 THEN
		RAISE NOTICE 'NENHUM FUNCIONARIO TRABALHA PARA ESSE GERENTE';
	ELSE
		RAISE NOTICE 'TIVERAM AUMENTO %', RES;
	END IF;
END;
$$

4-
SELECT * INTO COPY_DEPT FROM DEPARTMENTS WHERE department_id = -1;

MERGE COPY_DEPT COP

USING (SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID
       FROM DEPARTMENTS
       WHERE DEPARTMENT_ID = 10) AS DEP

ON DEP.DEPARTMENT_ID = COP.DEPARTMENT_ID

WHEN MATCHED 
  UPDATE SET DEPARTMENT_ID = DEP.DEPARTMENT_ID, DEPARTMENT_NAME = DEP.DEPARTMENT_NAME, MANAGER_ID = DEP.MANAGER_ID, LOCATION_ID = DEP.LOCATION_ID

WHEN NOT MATCHED
  INSERT (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
  VALUES (DEP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME, DEP.MANAGER_ID, DEP.LOCATION_ID;
	
	
5-
DO
$$
DECLARE
	COD_EMP INTEGER := 100;
	PER NUMERIC(10, 2) := 1.2;
	NOME EMPLOYEES.FIRST_NAME%TYPE;
	SALARIO EMPLOYEES.SALARY%TYPE;
	NOVO_SALARIO EMPLOYEES.SALARY%TYPE;
BEGIN
	SELECT FIRST_NAME, SALARY INTO NOME, SALARIO FROM EMPLOYEES WHERE EMPLOYEE_ID = COD_EMP;
	NOVO_SALARIO = SALARIO * PER;
	RAISE NOTICE 'NOME: %, SALARIO: %, NOVO SALARIO: %', NOME, SALARIO, NOVO_SALARIO;
END;
$$

6-
DO
$$
DECLARE
	DEP_DESC DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
	SELECT DEPARTMENT_NAME INTO DEP_DESC FROM DEPARTMENTS WHERE DEPARTMENT_ID = 160;
	RAISE NOTICE '%', UPPER(DEP_DESC);
	RAISE NOTICE '%', LOWER(DEP_DESC);
	RAISE NOTICE '%', LENGTH(TRIM(DEP_DESC));
END;
$$

7-
DO
$$
DECLARE
	V_NOME EMPLOYEES.FIRST_NAME%TYPE;
	V_SOBRE EMPLOYEES.LAST_NAME%TYPE;
	V_DATA DATE;
BEGIN
	SELECT FIRST_NAME, LAST_NAME, HIRE_DATE INTO V_NOME, V_SOBRE, V_DATA FROM EMPLOYEES WHERE EMPLOYEE_ID = 200;
	RAISE NOTICE '%', TO_CHAR(V_DATA, 'DD" DE "MONTH" DE "YYYY');
END;
$$

8-
DO
$$
DECLARE
	V_ID DEPARTMENTS.DEPARTMENT_ID%TYPE;
	V_NOME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
	FOR I IN 10..260 BY 10 LOOP
		SELECT DEPARTMENT_ID, DEPARTMENT_NAME INTO V_ID, V_NOME FROM DEPARTMENTS WHERE DEPARTMENT_ID = I;
		RAISE NOTICE 'ID: %, NOME: %', V_ID, V_NOME;
	END LOOP;
END;
$$

9-
DO
$$
DECLARE
	RES INTEGER;
BEGIN
	DELETE COUNTRY_NAME FROM COUNTRIES WHERE REGION_ID = 1;
	GET DIAGNOSTICS RES = ROW_COUNT;
	RAISE NOTICE 'FORAM EXCLUIDOS %', RES;
END;
$$

10-
DO
$$
DECLARE
	V_IDADE INTEGER;
BEGIN
	SELECT EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM HIRE_DATE) INTO V_IDADE FROM EMPLOYEES WHERE EMPLOYEE_ID = 190;
	IF V_IDADE <= 10 THEN
		RAISE NOTICE '% : INFANTIL', V_IDADE;
	ELSIF V_IDADE > 10 AND V_IDADE <= 18 THEN
		RAISE NOTICE '% : JOVEM', V_IDADE;
	ELSE
		RAISE NOTICE '% : ADULTO', V_IDADE;
	END IF;
END;
$$