DECLARE
	COUNTRY_RECORD COUNTRIES%ROWTYPE;
BEGIN
	SELECT * INTO COUNTRY_RECORD FROM COUNTRIES WHERE COUNTRY_ID = 'CA';
	DBMS_OUTPUT.PUT_LINE('CODIGO: '|| COUNTRY_RECORD.COUNTRY_ID || ' NAME: '|| COUNTRY_RECORD.COUNTRY_NAME || ' REGION: ' || COUNTRY_RECORD.REGION_ID);
END;

DECLARE
	TYPE DEPT_TABLE_TYPE IS TABLE OF
	DEPARTMENTS.DEPARTMENT_NAME%TYPE
	INDEX BY PLS_INTEGER;
	
	MY_DEPT_TABLE DEPT_TABLE_TYPE%TYPE;
	
	DEPT_TABLE DEPT_TABLE_TYPE;
	
	LOOP_COUNT NUMBER := 10;
	DEPTNO NUMBER := 0;
BEGIN
	FOR I IN 0..9 LOOP
		SELECT DEPARTMENT_NAME INTO MY_DEPT_TABLE FROM DEPARTMENTS WHERE DEPARTMENT_ID = I;
		DEPT_TABLE(LOOP_COUNT) := MY_DEPT_TABLE;
		LOOP_COUNT := LOOP_COUNT + 10;
	END LOOP;
END;



DECLARE
	TYPE DEPT_TABLE_TYPE IS TABLE OF
	DEPARTMENTS.DEPARTMENT_NAME%TYPE
	INDEX BY PLS_INTEGER;
	--MY_DEPT_TABLE DEPT_TABLE_TYPE%TYPE;
	DEPT_TABLE DEPT_TABLE_TYPE;
	LOOP_COUNT NUMBER := 10;
	DEPTNO NUMBER := 0;
BEGIN
	WHILE LOOP_COUNT <= 100 LOOP
		SELECT DEPARTMENT_NAME INTO DEPT_TABLE(LOOP_COUNT) FROM DEPARTMENTS WHERE DEPARTMENT_ID = LOOP_COUNT;
		--DEPT_TABLE(LOOP_COUNT) := MY_DEPT_TABLE;
		LOOP_COUNT := LOOP_COUNT + 10;
		DEPTNO := DEPTNO + 1;
	END LOOP;
	FOR I IN DEPT_TABLE.FIRST..DEPT_TABLE.LAST LOOP
		IF DEPT_TABLE.EXISTS(I) THEN
			DBMS_OUTPUT.PUT_LINE(DEPT_TABLE(I));
		END IF;
	END LOOP;
END;


DECLARE
	TYPE DEPT_TABLE_TYPE IS TABLE OF
	DEPARTMENTS%ROWTYPE
	INDEX BY PLS_INTEGER;
	DEPT_TABLE DEPT_TABLE_TYPE;
	LOOP_COUNT NUMBER := 10;
	MAXID NUMBER;
BEGIN
	SELECT MAX(DEPARTMENT_ID) INTO MAXID FROM DEPARTMENTS;
	WHILE LOOP_COUNT <= MAXID LOOP
		SELECT * INTO DEPT_TABLE(LOOP_COUNT) FROM DEPARTMENTS WHERE DEPARTMENT_ID = LOOP_COUNT;		
		LOOP_COUNT := LOOP_COUNT + 10;
	END LOOP;
	FOR I IN DEPT_TABLE.FIRST..DEPT_TABLE.LAST LOOP
		IF DEPT_TABLE.EXISTS(I) THEN
			DBMS_OUTPUT.PUT_LINE('CODIGO: '||DEPT_TABLE(I).DEPARTMENT_ID||' NOME: '||DEPT_TABLE(I).DEPARTMENT_NAME||' MANAGER: '||DEPT_TABLE(I).MANAGER_ID||' LOCAL: '||DEPT_TABLE(I).LOCATION_ID);
		END IF;
	END LOOP;
END;