DO
$$
DECLARE
	EMP_CURSOR CURSOR (DEPARTAMENTO EMP.DEPARTMENT_ID%TYPE, GERENTE EMP.MANAGER_ID%TYPE) IS SELECT EMPLOYEE_ID, SALARY, MANAGER_ID, DEPARTMENT_ID
																							FROM EMP
																							WHERE
																							MANAGER_ID = GERENTE
																							OR
																							DEPARTMENT_ID = DEPARTAMENTO
																							FOR UPDATE;
	V_DEPARTAMENTO EMP.DEPARTMENT_ID%TYPE := 50;
	V_GERENTE EMP.MANAGER_ID%TYPE := 100;
	V_SALARIO EMP.SALARY%TYPE;
	V_PERCENTUAL INT := 5;
	V_BONUS INT := 0;
BEGIN
	FOR EMP_RECORD IN EMP_CURSOR(V_DEPARTAMENTO,V_GERENTE) LOOP
		IF EMP_RECORD.DEPARTMENT_ID = V_DEPARTAMENTO AND EMP_RECORD.MANAGER_ID = V_GERENTE THEN
			V_BONUS := 3;
		ELSE
			IF EMP_RECORD.MANAGER_ID = V_GERENTE THEN
				V_BONUS := 2;
			END IF;
		END IF;
		RAISE NOTICE 'ID: %, SALARIO: %', EMP_RECORD.EMPLOYEE_ID, EMP_RECORD.SALARY;
		V_SALARIO := EMP_RECORD.SALARY + (EMP_RECORD.SALARY * (V_PERCENTUAL + V_BONUS)/100);
		RAISE NOTICE 'ID: %, SALARIO: %', EMP_RECORD.EMPLOYEE_ID, V_SALARIO;
		--UPDATE EMP SET SALARY = V_SALARIO WHERE CURRENT OF EMP_CURSOR;
	END LOOP;
END;
$$

----------------------------------------------------------------------------------

DO
$$
DECLARE
	EMP_CURSOR CURSOR (DEPARTAMENTO EMPLOYEES.DEPARTMENT_ID%TYPE) IS SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE	DEPARTMENT_ID = DEPARTAMENTO;
	V_DEPARTAMENTO EMPLOYEES.DEPARTMENT_ID%TYPE := 50;
	V_AVGSALARIO EMPLOYEES.SALARY%TYPE;
	V_SALARIO EMPLOYEES.SALARY%TYPE;
	V_PERCENTUAL NUMERIC;
BEGIN
	SELECT AVG(SALARY) INTO V_AVGSALARIO FROM EMPLOYEES WHERE DEPARTMENT_ID = V_DEPARTAMENTO;
	FOR EMP_RECORD IN EMP_CURSOR(V_DEPARTAMENTO) LOOP
		IF V_AVGSALARIO >= 0 AND V_AVGSALARIO < 3000 THEN
			V_PERCENTUAL := 1.05;
		ELSE
			IF V_AVGSALARIO >= 3000 AND V_AVGSALARIO < 7000 THEN
				V_PERCENTUAL := 1.04;
			ELSE
				V_PERCENTUAL := 1.035;
			END IF;
		END IF;
		RAISE NOTICE 'ID: %, SALARIO: %', EMP_RECORD.FIRST_NAME, EMP_RECORD.SALARY;
		V_SALARIO := EMP_RECORD.SALARY * V_PERCENTUAL;
		RAISE NOTICE 'ID: %, SALARIO: %', EMP_RECORD.FIRST_NAME, V_SALARIO;
	END LOOP;
END;
$$